SELECT	SUM(TDAUX.VALOR_SAIDA) AS VSAI,
			SUM(COALESCE(TDEFIMPSAI_2_30.VALOR_IMPOSTO, 0)) AS VIPI,
			SUM(COALESCE(TD_IMP_9.VALOR_IMPOSTO, 0)) AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
 	 FROM BETHADBA.EFSAIDAS AS EFSAIDAS INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFSAIDAS.CODI_EMP INNER JOIN
			BETHADBA.EFPARAMETRO_VIGENCIA AS EFPARAMETRO_VIGENCIA
		ON EFPARAMETRO_VIGENCIA.CODI_EMP = EFSAIDAS.CODI_EMP INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFSAIDAS.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFSAIDAS.CODI_ACU,
			LATERAL(SELECT SUM(VLOR_ECA) AS VLOR_ECA
						 FROM BETHADBA.EFTABECFM M INNER JOIN
								BETHADBA.EFTABECFA A
							ON M.CODI_EMP = A.CODI_EMP AND
								M.CODI_ECM = A.CODI_ECM AND
								M.CODI_MEC = A.CODI_MEC AND
								M.TIPO_ECM = A.TIPO_ECM
						WHERE M.CODI_EMP = EFSAIDAS.CODI_EMP AND
								M.CODI_ECM = EFSAIDAS.CODI_SAI AND
								M.TIPO_ECM = 'S' AND
								M.DEDUZIR_ECM = 'S' AND
								A.SITU_ECA IN ('DESC', 'CANC')) AS TD_ECF,
			LATERAL(SELECT SUM(VLOR_ISA) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPSAI AS EFIMPSAI
						WHERE EFIMPSAI.CODI_EMP = EFSAIDAS.CODI_EMP AND
								EFIMPSAI.CODI_SAI = EFSAIDAS.CODI_SAI AND
								EFIMPSAI.CODI_IMP IN (2, 30)) AS TDEFIMPSAI_2_30,
			LATERAL(SELECT SUM(VLOR_ISA) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPSAI AS EFIMPSAI INNER JOIN
								BETHADBA.EFPARAMETRO_VIGENCIA AS EFPARAMETRO_VIGENCIA
							ON EFPARAMETRO_VIGENCIA.CODI_EMP = EFIMPSAI.CODI_EMP
						WHERE EFIMPSAI.CODI_EMP = EFSAIDAS.CODI_EMP AND
								EFIMPSAI.CODI_SAI = EFSAIDAS.CODI_SAI AND
								EFIMPSAI.CODI_IMP = 9 AND
								EFPARAMETRO_VIGENCIA.VIGENCIA_PAR = DSDBA.D_BUSCA_VIGENCIA_PARAMETRO(EFSAIDAS.CODI_EMP, EFSAIDAS.DSAI_SAI)) AS TD_IMP_9,
			LATERAL(SELECT EFSAIDAS.VCON_SAI - COALESCE(TD_ECF.VLOR_ECA, 0) AS VALOR_SAIDA,
								MONTH(EFSAIDAS.DSAI_SAI) AS MES,
								YEAR(EFSAIDAS.DSAI_SAI) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP, 
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE EFSAIDAS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFSAIDAS.DSAI_SAI >= :DATINI AND
			EFSAIDAS.DSAI_SAI <= :DATFIN AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			EFSAIDAS.CODI_NAT NOT IN (5933, 6933) AND
			EFSAIDAS.NOVO_ECF = 'N' AND
			(EFPARAMETRO_VIGENCIA.EMPRESA_REVENDA_VEICULOS = 'N' OR
				NOT (EFPARAMETRO_VIGENCIA.EMPRESA_REVENDA_VEICULOS = 'S' AND  
			      (EFACUMULADOR_VIGENCIA.OPERACAO_VEICULOS_USADOS_ACU = 'S' OR EFSAIDAS.CODI_NAT IN (5115, 6115)))) AND
			EFPARAMETRO_VIGENCIA.VIGENCIA_PAR = DSDBA.D_BUSCA_VIGENCIA_PARAMETRO(EFSAIDAS.CODI_EMP, EFSAIDAS.DSAI_SAI) AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFSAIDAS.CODI_EMP, EFSAIDAS.CODI_ACU, EFSAIDAS.DSAI_SAI)
GROUP BY EFSAIDAS.DSAI_SAI, TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP,
			GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP, GEEMPRE.RLEG_EMP, 
			GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT SUM(TD_VALOR_CONTABIL.VALOR_CONTABIL) AS VSAI,
			SUM(COALESCE(TDEFIMPSAI_2_30.VALOR_IMPOSTO, 0)) AS VIPI,
			SUM(COALESCE(TD_IMP_9.VALOR_IMPOSTO, 0)) AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
 	 FROM BETHADBA.EFSAIDAS AS EFSAIDAS INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFSAIDAS.CODI_EMP INNER JOIN
			BETHADBA.EFPARAMETRO_VIGENCIA AS EFPARAMETRO_VIGENCIA
		ON EFPARAMETRO_VIGENCIA.CODI_EMP = EFSAIDAS.CODI_EMP INNER JOIN 
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA 
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFSAIDAS.CODI_EMP AND 
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFSAIDAS.CODI_ACU INNER JOIN 
			BETHADBA.EFMVSPRO AS EFMVSPRO
		ON	EFMVSPRO.CODI_EMP = EFSAIDAS.CODI_EMP AND 
			EFMVSPRO.CODI_SAI = EFSAIDAS.CODI_SAI INNER JOIN
			BETHADBA.EFPRODUTOS AS EFPRODUTOS 
		ON	EFPRODUTOS.CODI_EMP = EFMVSPRO.CODI_EMP AND 
			EFPRODUTOS.CODI_PDI = EFMVSPRO.CODI_PDI,
			LATERAL(SELECT SUM(VLOR_ECA) AS VLOR_ECA
						 FROM BETHADBA.EFTABECFM M INNER JOIN
								BETHADBA.EFTABECFA A
							ON M.CODI_EMP = A.CODI_EMP AND
								M.CODI_ECM = A.CODI_ECM AND
								M.CODI_MEC = A.CODI_MEC AND
								M.TIPO_ECM = A.TIPO_ECM
						WHERE M.CODI_EMP = EFSAIDAS.CODI_EMP AND
								M.CODI_ECM = EFSAIDAS.CODI_SAI AND
								M.TIPO_ECM = 'S' AND
								M.DEDUZIR_ECM = 'S' AND
								A.SITU_ECA IN ('DESC', 'CANC')) AS TD_ECF,
			LATERAL(SELECT SUM(VLOR_ISA) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPSAI AS EFIMPSAI
						WHERE EFIMPSAI.CODI_EMP = EFSAIDAS.CODI_EMP AND
								EFIMPSAI.CODI_SAI = EFSAIDAS.CODI_SAI AND
								EFIMPSAI.CODI_IMP IN (2, 30)) AS TDEFIMPSAI_2_30,
			LATERAL(SELECT SUM(VLOR_ISA) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPSAI AS EFIMPSAI INNER JOIN
								BETHADBA.EFPARAMETRO_VIGENCIA AS EFPARAMETRO_VIGENCIA
							ON EFPARAMETRO_VIGENCIA.CODI_EMP = EFIMPSAI.CODI_EMP
						WHERE EFIMPSAI.CODI_EMP = EFSAIDAS.CODI_EMP AND
								EFIMPSAI.CODI_SAI = EFSAIDAS.CODI_SAI AND
								EFIMPSAI.CODI_IMP = 9 AND
								EFPARAMETRO_VIGENCIA.VIGENCIA_PAR = DSDBA.D_BUSCA_VIGENCIA_PARAMETRO(EFSAIDAS.CODI_EMP, EFSAIDAS.DSAI_SAI)) AS TD_IMP_9,
			LATERAL(SELECT EFSAIDAS.VCON_SAI - COALESCE(TD_ECF.VLOR_ECA, 0) AS VALOR_SAIDA,
								MONTH(EFSAIDAS.DSAI_SAI) AS MES,
								YEAR(EFSAIDAS.DSAI_SAI) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT COALESCE(SUM(EFMVEPRO.VALOR_CONTABIL_MEP), 0) AS VALOR_CONTABIL
						 FROM BETHADBA.EFMVEPRO AS EFMVEPRO
						WHERE EFMVEPRO.CODI_EMP = EFMVSPRO.CODI_EMP AND
								EFMVEPRO.CODI_PDI = EFMVSPRO.CODI_PDI AND
								EFMVEPRO.CODI_ENT = (SELECT MAX(EFMVEPRO2.CODI_ENT)
															  FROM BETHADBA.EFMVEPRO AS EFMVEPRO2
															 WHERE EFMVEPRO2.CODI_EMP = EFMVEPRO.CODI_EMP AND
																	 EFMVEPRO2.CODI_PDI = EFMVEPRO.CODI_PDI AND
																	 EFMVEPRO2.CODI_SAI_DEVOLVIDA IS NULL AND
																	 EFMVEPRO2.DATA_MEP <= EFSAIDAS.DSAI_SAI AND
																	 EFMVEPRO2.DATA_MEP < DATE(:DATFIN))) AS TD_ENTRADA,
			LATERAL(SELECT (CASE WHEN :EXLUIR_CUSTO_AQUISICAO_VEICULO = 'S' THEN
      			            (CASE WHEN COALESCE(EFMVSPRO.VALOR_CONTABIL_MSP, 0) > COALESCE(TD_ENTRADA.VALOR_CONTABIL, 0) THEN 
      							      (COALESCE(EFMVSPRO.VALOR_CONTABIL_MSP, 0) - COALESCE(TD_ENTRADA.VALOR_CONTABIL, 0)) 
      								  ELSE 
      									  CAST(0 AS DECIMAL(13, 4))
      								  END)
      							  ELSE
      								  COALESCE(EFMVSPRO.VALOR_CONTABIL_MSP, 0) 
      								END) AS VALOR_CONTABIL
						 FROM DSDBA.DUMMY) AS TD_VALOR_CONTABIL,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR 
	WHERE EFSAIDAS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFSAIDAS.DSAI_SAI >= :DATINI AND
			EFSAIDAS.DSAI_SAI <= :DATFIN AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			EFSAIDAS.CODI_NAT NOT IN (5933, 6933) AND
			EFSAIDAS.NOVO_ECF = 'N' AND
			EFPARAMETRO_VIGENCIA.EMPRESA_REVENDA_VEICULOS = 'S' AND 
			(EFACUMULADOR_VIGENCIA.OPERACAO_VEICULOS_USADOS_ACU = 'S' OR EFSAIDAS.CODI_NAT IN (5115, 6115)) AND
			EFPARAMETRO_VIGENCIA.VIGENCIA_PAR = DSDBA.D_BUSCA_VIGENCIA_PARAMETRO(EFSAIDAS.CODI_EMP, EFSAIDAS.DSAI_SAI) AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFSAIDAS.CODI_EMP, EFSAIDAS.CODI_ACU, EFSAIDAS.DSAI_SAI)
GROUP BY EFSAIDAS.DSAI_SAI, TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP,
			GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP, GEEMPRE.RLEG_EMP,	
			GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT SUM(SITUACAO.VALOR) AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
 	 FROM BETHADBA.EFECF_REDUCAO_Z AS REDUCAO_Z INNER JOIN
			BETHADBA.EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA_DETALHAMENTO AS SITUACAO
 	   ON SITUACAO.CODI_EMP = REDUCAO_Z.CODI_EMP AND
			SITUACAO.I_REDUCAO = REDUCAO_Z.I_REDUCAO INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = REDUCAO_Z.CODI_EMP INNER JOIN
			BETHADBA.EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA AS EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA
		ON EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.CODI_EMP = SITUACAO.CODI_EMP AND
			EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.I_REDUCAO = SITUACAO.I_REDUCAO AND
			EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.I_SITUACAO = SITUACAO.I_SITUACAO,
			LATERAL(SELECT MONTH(REDUCAO_Z.DATA_REDUCAO) AS MES,
								YEAR(REDUCAO_Z.DATA_REDUCAO) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE REDUCAO_Z.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			REDUCAO_Z.DATA_REDUCAO >= :DATINI AND
			REDUCAO_Z.DATA_REDUCAO <= :DATFIN AND
			EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.OPERACAO IN (1, 2, 3, 7)
GROUP BY REDUCAO_Z.DATA_REDUCAO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.MES,
			GEEMPRE.CGCE_EMP, TDAUX.ANO, TDAUX.CIDAEMP, TDAUX.CEPE_EMP, GEEMPRE.RLEG_EMP, 
			GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT 0 AS VSAI,
			0 AS VIPI,
			0 AS VST,
			SUM(SITUACAO.VALOR) AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
 	 FROM BETHADBA.EFECF_REDUCAO_Z AS REDUCAO_Z INNER JOIN
			BETHADBA.EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA_DETALHAMENTO AS SITUACAO
 	   ON SITUACAO.CODI_EMP = REDUCAO_Z.CODI_EMP AND
			SITUACAO.I_REDUCAO = REDUCAO_Z.I_REDUCAO INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = REDUCAO_Z.CODI_EMP INNER JOIN 
			BETHADBA.EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA AS EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA
		ON EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.CODI_EMP = SITUACAO.CODI_EMP AND
			EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.I_REDUCAO = SITUACAO.I_REDUCAO AND
			EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.I_SITUACAO = SITUACAO.I_SITUACAO,
			LATERAL(SELECT MONTH(REDUCAO_Z.DATA_REDUCAO) AS MES,
								YEAR(REDUCAO_Z.DATA_REDUCAO) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE REDUCAO_Z.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			REDUCAO_Z.DATA_REDUCAO >= :DATINI AND
			REDUCAO_Z.DATA_REDUCAO <= :DATFIN AND
			EFECF_REDUCAO_Z_SITUACAO_TRIBUTARIA.OPERACAO IN (8, 9, 10)
GROUP BY REDUCAO_Z.DATA_REDUCAO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.MES,
			GEEMPRE.CGCE_EMP, TDAUX.ANO, TDAUX.CIDAEMP, TDAUX.CEPE_EMP, GEEMPRE.RLEG_EMP, 
			GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT SUM(REDUCAO_Z_BILHETE.VENDA_LIQUIDA) AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
 	 FROM BETHADBA.EFECF_REDUCAO_Z_BILHETE AS REDUCAO_Z_BILHETE INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = REDUCAO_Z_BILHETE.CODI_EMP,
			LATERAL(SELECT MONTH(REDUCAO_Z_BILHETE.DATA_REDUCAO) AS MES,
								YEAR(REDUCAO_Z_BILHETE.DATA_REDUCAO) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE REDUCAO_Z_BILHETE.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			REDUCAO_Z_BILHETE.DATA_REDUCAO >= :DATINI AND
			REDUCAO_Z_BILHETE.DATA_REDUCAO <= :DATFIN
GROUP BY REDUCAO_Z_BILHETE.DATA_REDUCAO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.MES,
			GEEMPRE.CGCE_EMP, TDAUX.ANO, TDAUX.CIDAEMP, TDAUX.CEPE_EMP, GEEMPRE.RLEG_EMP, 
			GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT SUM(RESUMO_BILHETE.VALOR_TOTAL) AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
 	 FROM BETHADBA.EFRESUMO_MOVIMENTO_DIARIO AS RESUMO INNER JOIN
			BETHADBA.EFRESUMO_MOVIMENTO_DIARIO_BILHETE AS RESUMO_BILHETE
		ON	RESUMO.CODI_EMP = RESUMO_BILHETE.CODI_EMP AND
			RESUMO.I_RESUMO = RESUMO_BILHETE.I_RESUMO INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = RESUMO_BILHETE.CODI_EMP INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = RESUMO_BILHETE.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = RESUMO_BILHETE.CODI_ACU,
			LATERAL(SELECT	MONTH(RESUMO.DATA_EMISSAO) AS MES,
								YEAR(RESUMO.DATA_EMISSAO) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE RESUMO.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			RESUMO.DATA_EMISSAO >= :DATINI AND
			RESUMO.DATA_EMISSAO <= :DATFIN AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			RESUMO_BILHETE.CODI_NAT NOT IN(5933, 6933) AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(RESUMO_BILHETE.CODI_EMP, RESUMO_BILHETE.CODI_ACU, RESUMO.DATA_EMISSAO)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP,
			GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP, GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, 
			TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT SUM(BILHETE.VALOR_TOTAL) AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
 	 FROM BETHADBA.EFBILHETE_PASSAGEM AS BILHETE INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = BILHETE.CODI_EMP INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = BILHETE.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = BILHETE.CODI_ACU,
			LATERAL(SELECT MONTH(BILHETE.DATA_EMISSAO) AS MES,
								YEAR(BILHETE.DATA_EMISSAO) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE BILHETE.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			BILHETE.DATA_EMISSAO >= :DATINI AND
			BILHETE.DATA_EMISSAO <= :DATFIN AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			BILHETE.CODI_NAT NOT IN(5933, 6933) AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(BILHETE.CODI_EMP, BILHETE.CODI_ACU, BILHETE.DATA_EMISSAO)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP, 
         GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT 0 AS VSAI,
			0 AS VIPI,
			0 AS VST,
			SUM(TDAUX.VSER) AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFSERVICOS AS EFSERVICOS INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFSERVICOS.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFSERVICOS.CODI_ACU INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFSERVICOS.CODI_EMP,
			LATERAL(SELECT SUM(A.VLOR_ECA ) AS VALOR_CANCELAMENT_DESCONTO
						 FROM BETHADBA.EFTABECFM M, BETHADBA.EFTABECFA A
						WHERE M.TIPO_ECM = 'V' AND
								M.DEDUZIR_ECM = 'S' AND
								M.CODI_EMP = A.CODI_EMP AND
								M.CODI_ECM = A.CODI_ECM AND
								M.CODI_MEC = A.CODI_MEC AND
								M.TIPO_ECM = A.TIPO_ECM AND
								A.SITU_ECA IN ( 'DESC', 'CANC' ) AND
								M.CODI_EMP = EFSERVICOS.CODI_EMP AND
								M.CODI_ECM = EFSERVICOS.CODI_SER) AS TDCANCELAMENTO_DESCONTO,
			LATERAL(SELECT CASE
									WHEN EFSERVICOS.VCON_SER - COALESCE(TDCANCELAMENTO_DESCONTO.VALOR_CANCELAMENT_DESCONTO, 0) > 0 THEN
										EFSERVICOS.VCON_SER - COALESCE(TDCANCELAMENTO_DESCONTO.VALOR_CANCELAMENT_DESCONTO, 0)
									ELSE 0
								END AS VSER,
								MONTH(EFSERVICOS.DSER_SER) AS MES,
								YEAR(EFSERVICOS.DSER_SER) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	 WHERE EFSERVICOS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			 EFSERVICOS.DSER_SER >= :DATINI AND
			 EFSERVICOS.DSER_SER <= :DATFIN AND
			 EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			 EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFSERVICOS.CODI_EMP, EFSERVICOS.CODI_ACU, EFSERVICOS.DSER_SER)
 GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP, 
          GEEMPRE.RLEG_EMP,	GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT 0 AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			SUM(EFMOVACU.VLOR_MAC) AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFMOVACU AS EFMOVACU INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFMOVACU.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFMOVACU.CODI_ACU INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFMOVACU.CODI_EMP,
			LATERAL(SELECT MONTH(EFMOVACU.DATA_MAC) AS MES,
								YEAR(EFMOVACU.DATA_MAC) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE EFMOVACU.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFMOVACU.DATA_MAC >= :DATINI AND
			EFMOVACU.DATA_MAC <= :DATFIN AND
			EFMOVACU.OPER_MAC IN (1, 2, 6, 9) AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFMOVACU.CODI_EMP, EFMOVACU.CODI_ACU, EFMOVACU.DATA_MAC)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP,
         GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT -SUM(EFENTRADAS.VCON_ENT) AS VSAI,
			-SUM(COALESCE(TDIMPOSTO_PIS.VALOR_IMPOSTO, 0)) AS VIPI,
			-SUM(COALESCE(TDIMPOSTO_9.VALOR_IMPOSTO, 0)) AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFENTRADAS AS EFENTRADAS INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFENTRADAS.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFENTRADAS.CODI_ACU INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFENTRADAS.CODI_EMP,
			LATERAL(SELECT SUM(EFIMPENT.VLOR_IEN) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPENT AS EFIMPENT
						WHERE EFIMPENT.CODI_EMP = EFENTRADAS.CODI_EMP AND
								EFIMPENT.CODI_ENT = EFENTRADAS.CODI_ENT AND
								EFIMPENT.CODI_IMP IN (2, 30)) TDIMPOSTO_PIS,
			 LATERAL(SELECT SUM(IMPOSTO_9.VLOR_IEN) AS VALOR_IMPOSTO
						  FROM BETHADBA.EFIMPENT AS IMPOSTO_9
						 WHERE IMPOSTO_9.CODI_EMP = EFENTRADAS.CODI_EMP AND
								 IMPOSTO_9.CODI_ENT = EFENTRADAS.CODI_ENT AND
								 IMPOSTO_9.CODI_IMP = 9) AS TDIMPOSTO_9,
			LATERAL(SELECT MONTH(EFENTRADAS.DENT_ENT) AS MES,
								YEAR(EFENTRADAS.DENT_ENT) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE EFENTRADAS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFENTRADAS.DENT_ENT >= :DATINI AND
			EFENTRADAS.DENT_ENT <= :DATFIN AND
			EFENTRADAS.CODI_NAT NOT IN (1933,  2933 ) AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			EFACUMULADOR_VIGENCIA.IDEV_ACU = 'S' AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFENTRADAS.CODI_EMP, EFENTRADAS.CODI_ACU, EFENTRADAS.DENT_ENT)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP,
         GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT 0 AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			-SUM(EFMOVACU.VLOR_MAC) AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFMOVACU AS EFMOVACU INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFMOVACU.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFMOVACU.CODI_ACU INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFMOVACU.CODI_EMP,
			LATERAL(SELECT	MONTH(EFMOVACU.DATA_MAC) AS MES,
								YEAR(EFMOVACU.DATA_MAC) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE EFMOVACU.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFMOVACU.DATA_MAC >= :DATINI AND
			EFMOVACU.DATA_MAC <= :DATFIN AND
			EFMOVACU.OPER_MAC IN (3, 4, 5) AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFMOVACU.CODI_EMP, EFMOVACU.CODI_ACU, EFMOVACU.DATA_MAC)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP,
         GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
	SELECT 0 AS VSAI,
			 SUM(COALESCE(TDIMPOSTO_IPI.VALOR_IMPOSTO, 0)) AS VIPI,
			 0 AS VST,
			 SUM(TDAUX.VSER) AS VSER,
			 0 AS VOUT,
			 TDAUX.MES AS MES,
			 TDAUX.ANO AS ANO,
			 TDAUX.ENDE_EMP AS ENDE_EMP,
			 GEEMPRE.IEST_EMP,
			 TDAUX.CIDAEMP AS CIDAEMP,
			 GEEMPRE.CGCE_EMP,
			 TDAUX.CEPE_EMP AS CEPE_EMP,
			 GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFSAIDAS AS EFSAIDAS INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFSAIDAS.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFSAIDAS.CODI_ACU INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFSAIDAS.CODI_EMP,
			LATERAL(SELECT SUM(EFIMPSAI.VLOR_ISA) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPSAI AS EFIMPSAI
						WHERE EFIMPSAI.CODI_EMP = EFSAIDAS.CODI_EMP AND
								EFIMPSAI.CODI_SAI = EFSAIDAS.CODI_SAI AND
								EFIMPSAI.CODI_IMP = 2) AS TDIMPOSTO_IPI,
			LATERAL(SELECT SUM(A.VLOR_ECA) AS VALOR_DESCONTO
						 FROM BETHADBA.EFTABECFM M,
								BETHADBA.EFTABECFA A
						WHERE M.TIPO_ECM = 'S' AND
								M.DEDUZIR_ECM = 'S' AND
								M.CODI_EMP = A.CODI_EMP AND
								M.CODI_ECM = A.CODI_ECM AND
								M.CODI_MEC = A.CODI_MEC AND
								M.TIPO_ECM = A.TIPO_ECM AND
								A.SITU_ECA IN ('DESC', 'CANC') AND
								M.CODI_EMP = EFSAIDAS.CODI_EMP AND
								M.CODI_ECM = EFSAIDAS.CODI_SAI) AS TDCANCELAMENTO_DESCONTO,
			LATERAL(SELECT CASE
									WHEN EFSAIDAS.VCON_SAI - COALESCE(TDCANCELAMENTO_DESCONTO.VALOR_DESCONTO, 0) > 0  THEN
										EFSAIDAS.VCON_SAI - COALESCE(TDCANCELAMENTO_DESCONTO.VALOR_DESCONTO, 0)
									ELSE 0
								END AS VSER,
								MONTH(EFSAIDAS.DSAI_SAI) AS MES,
								YEAR(EFSAIDAS.DSAI_SAI) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE EFSAIDAS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFSAIDAS.DSAI_SAI >= :DATINI AND
			EFSAIDAS.DSAI_SAI <= :DATFIN AND
			EFSAIDAS.CODI_NAT IN (5933, 6933 ) AND
			EFSAIDAS.NOVO_ECF = 'N' AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFSAIDAS.CODI_EMP, EFSAIDAS.CODI_ACU, EFSAIDAS.DSAI_SAI)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP,
         GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT 0 AS VSAI,
			-SUM(COALESCE(TDIMPOSTO_PIS.VALOR_IMPOSTO, 0)) AS VIPI,
			0 AS VST,
			-SUM(EFENTRADAS.VCON_ENT) AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			GEEMPRE.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			GEEMPRE.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFENTRADAS AS EFENTRADAS INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFENTRADAS.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFENTRADAS.CODI_ACU INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFENTRADAS.CODI_EMP,
			LATERAL(SELECT SUM(EFIMPENT.VLOR_IEN) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPENT AS EFIMPENT
						WHERE EFIMPENT.CODI_EMP = EFENTRADAS.CODI_EMP AND
								EFIMPENT.CODI_ENT = EFENTRADAS.CODI_ENT AND
								EFIMPENT.CODI_IMP IN (2, 30)) AS TDIMPOSTO_PIS,
			LATERAL(SELECT MONTH(EFENTRADAS.DENT_ENT) AS MES,
								YEAR(EFENTRADAS.DENT_ENT) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE EFENTRADAS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFENTRADAS.DENT_ENT >= :DATINI AND
			EFENTRADAS.DENT_ENT <= :DATFIN AND
			EFENTRADAS.CODI_NAT IN (1933, 2933 ) AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'S' AND
			EFACUMULADOR_VIGENCIA.IDEV_ACU = 'S' AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFENTRADAS.CODI_EMP, EFENTRADAS.CODI_ACU, EFENTRADAS.DENT_ENT)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP,
         GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
	SELECT  0 AS VSAI,
			 SUM(COALESCE(TDIMPOSTO_IPI.VALOR_IMPOSTO, 0)) AS VIPI,
			 0 AS VST,
			 0 AS VSER,
			 0 AS VOUT,
			 TDAUX.MES AS MES,
			 TDAUX.ANO AS ANO,
			 TDAUX.ENDE_EMP AS ENDE_EMP,
			 GEEMPRE.IEST_EMP,
			 TDAUX.CIDAEMP AS CIDAEMP,
			 GEEMPRE.CGCE_EMP,
			 TDAUX.CEPE_EMP AS CEPE_EMP,
			 GEEMPRE.RLEG_EMP AS RLEG_EMP,
			GEEMPRE.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			GEEMPRE.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFSAIDAS AS EFSAIDAS INNER JOIN
			BETHADBA.EFACUMULADOR_VIGENCIA AS EFACUMULADOR_VIGENCIA
		ON EFACUMULADOR_VIGENCIA.CODI_EMP = EFSAIDAS.CODI_EMP AND
			EFACUMULADOR_VIGENCIA.CODI_ACU = EFSAIDAS.CODI_ACU INNER JOIN
			BETHADBA.GEEMPRE AS GEEMPRE
		ON GEEMPRE.CODI_EMP = EFSAIDAS.CODI_EMP,
			LATERAL(SELECT SUM(EFIMPSAI.VLOR_ISA) AS VALOR_IMPOSTO
						 FROM BETHADBA.EFIMPSAI AS EFIMPSAI
						WHERE EFIMPSAI.CODI_EMP = EFSAIDAS.CODI_EMP AND
								EFIMPSAI.CODI_SAI = EFSAIDAS.CODI_SAI AND
								EFIMPSAI.CODI_IMP = 2) AS TDIMPOSTO_IPI,
			LATERAL(SELECT MONTH(EFSAIDAS.DSAI_SAI) AS MES,
								YEAR(EFSAIDAS.DSAI_SAI) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = GEEMPRE.CODI_CON) AS TD_CONTADOR
	WHERE EFSAIDAS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			EFSAIDAS.DSAI_SAI >= :DATINI AND
			EFSAIDAS.DSAI_SAI <= :DATFIN AND
			EFSAIDAS.CODI_NAT IN (5929, 6929) AND
			EFSAIDAS.NOVO_ECF = 'N' AND
			EFACUMULADOR_VIGENCIA.IFAT_ACU = 'N' AND
			EFACUMULADOR_VIGENCIA.VIGENCIA_ACU = DSDBA.D_BUSCA_VIGENCIA_ACUMULADOR(EFSAIDAS.CODI_EMP, EFSAIDAS.CODI_ACU, EFSAIDAS.DSAI_SAI)
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, GEEMPRE.IEST_EMP, TDAUX.CIDAEMP, GEEMPRE.CGCE_EMP, TDAUX.CEPE_EMP,
         GEEMPRE.RLEG_EMP, GEEMPRE.CPF_LEG_EMP, GEEMPRE.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT SUM(TDAUX.VALOR_SAIDAS) AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			EMPRESA.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			EMPRESA.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			EMPRESA.RLEG_EMP AS RLEG_EMP,
			EMPRESA.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			EMPRESA.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFEMPREENDIMENTOS_IMOBILIARIOS_CONTRATOS_VENDA_PAGAMENTOS AS PAGAMENTOS INNER JOIN 
			BETHADBA.EFEMPREENDIMENTOS_IMOBILIARIOS_CONTRATOS_VENDA_PARCELAS AS PARCELAS
		ON PARCELAS.CODI_EMP = PAGAMENTOS.CODI_EMP AND
			PARCELAS.I_CONTRATO = PAGAMENTOS.I_CONTRATO AND
			PARCELAS.I_PARCELA = PAGAMENTOS.I_PARCELA INNER JOIN
			BETHADBA.EFEMPREENDIMENTOS_IMOBILIARIOS_CONTRATOS_VENDA AS CONTRATO_VENDA
		ON CONTRATO_VENDA.CODI_EMP = PARCELAS.CODI_EMP AND
			CONTRATO_VENDA.I_CONTRATO = PARCELAS.I_CONTRATO INNER JOIN
			BETHADBA.EFEMPREENDIMENTOS_IMOBILIARIOS AS EMPREENDIMENTO
		ON	EMPREENDIMENTO.CODI_EMP = CONTRATO_VENDA.CODI_EMP AND
			EMPREENDIMENTO.I_EMPREENDIMENTO = CONTRATO_VENDA.I_EMPREENDIMENTO INNER JOIN
			BETHADBA.GEEMPRE AS EMPRESA
		ON EMPRESA.CODI_EMP = PAGAMENTOS.CODI_EMP,
	 		LATERAL(SELECT MONTH(PAGAMENTOS.DATA_PAGAMENTO) AS MES,
								YEAR(PAGAMENTOS.DATA_PAGAMENTO) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP,
								CASE EMPREENDIMENTO.CALCULAR_PIS_COFINS_CORRECAO_MONETARIA
									WHEN 'S' THEN PAGAMENTOS.VALOR_PAGO - PAGAMENTOS.VALOR_JUROS - PAGAMENTOS.VALOR_MULTA + PAGAMENTOS.VALOR_DEVOLUCAO
									ELSE PAGAMENTOS.VALOR_PAGO - PAGAMENTOS.VALOR_CORRECAO - PAGAMENTOS.VALOR_JUROS - PAGAMENTOS.VALOR_MULTA + PAGAMENTOS.VALOR_DEVOLUCAO
								END AS VALOR_SAIDAS
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = EMPRESA.CODI_CON) AS TD_CONTADOR
	WHERE PAGAMENTOS.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			PAGAMENTOS.DATA_PAGAMENTO >= :DATINI AND
			PAGAMENTOS.DATA_PAGAMENTO <= :DATFIN
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, EMPRESA.IEST_EMP, TDAUX.CIDAEMP, EMPRESA.CGCE_EMP, TDAUX.CEPE_EMP,
         EMPRESA.RLEG_EMP, EMPRESA.CPF_LEG_EMP, EMPRESA.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
  SELECT -SUM(RESCISAO_CONTRATO_UNIDADES.VALOR_DEVOLVIDO) AS VSAI,
			0 AS VIPI,
			0 AS VST,
			0 AS VSER,
			0 AS VOUT,
			TDAUX.MES AS MES,
			TDAUX.ANO AS ANO,
			TDAUX.ENDE_EMP AS ENDE_EMP,
			EMPRESA.IEST_EMP,
			TDAUX.CIDAEMP AS CIDAEMP,
			EMPRESA.CGCE_EMP,
			TDAUX.CEPE_EMP AS CEPE_EMP,
			EMPRESA.RLEG_EMP AS RLEG_EMP,
			EMPRESA.CARGO_LEG_EMP AS CARGO_LEG_EMP,
			EMPRESA.CPF_LEG_EMP AS CPF_LEG_EMP,
			TD_CONTADOR.NOME_CON AS NOME_CON,
			TD_CONTADOR.RCRC_CON AS CRC_CON,
			TD_CONTADOR.CPF_CON AS CPF_CON
	 FROM BETHADBA.EFEMPREENDIMENTOS_IMOBILIARIOS_RESCISAO_CONTRATO AS RESCISAO_CONTRATO INNER JOIN
			BETHADBA.EFEMPREENDIMENTOS_IMOBILIARIOS_RESCISAO_CONTRATO_UNIDADES AS RESCISAO_CONTRATO_UNIDADES
		ON RESCISAO_CONTRATO_UNIDADES.CODI_EMP = RESCISAO_CONTRATO.CODI_EMP AND
			RESCISAO_CONTRATO_UNIDADES.I_RESCISAO = RESCISAO_CONTRATO.I_RESCISAO INNER JOIN
			BETHADBA.GEEMPRE AS EMPRESA
		ON EMPRESA.CODI_EMP = RESCISAO_CONTRATO.CODI_EMP,
	 		LATERAL(SELECT MONTH(RESCISAO_CONTRATO.DATA_DEVOLUCAO) AS MES,
								YEAR(RESCISAO_CONTRATO.DATA_DEVOLUCAO) AS ANO,
								CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
								CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
								CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
						 FROM DSDBA.DUMMY) AS TDAUX,
			LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
								     MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
								     MAX(CONTADOR.CPFC_CON) AS CPF_CON
						    FROM BETHADBA.GECONTADOR AS CONTADOR
						   WHERE CONTADOR.CODI_CON = EMPRESA.CODI_CON) AS TD_CONTADOR
	WHERE RESCISAO_CONTRATO.CODI_EMP IN (:ALLISTAEMPRESAS) AND
			RESCISAO_CONTRATO.DATA_DEVOLUCAO >= :DATINI AND
			RESCISAO_CONTRATO.DATA_DEVOLUCAO <= :DATFIN
GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, EMPRESA.IEST_EMP, TDAUX.CIDAEMP, EMPRESA.CGCE_EMP, TDAUX.CEPE_EMP,
         EMPRESA.RLEG_EMP, EMPRESA.CPF_LEG_EMP, EMPRESA.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
UNION ALL
	  SELECT -SUM(EFENTRADAS_EXTRA_PRODUTO.VALOR_PRODUTO) AS VSAI,
				0 AS VIPI,
				0 AS VST,
				0 AS VSER,
				0 AS VOUT,
				TDAUX.MES AS MES,
				TDAUX.ANO AS ANO,
				TDAUX.ENDE_EMP AS ENDE_EMP,
				EMPRESA.IEST_EMP,
				TDAUX.CIDAEMP AS CIDAEMP,
				EMPRESA.CGCE_EMP,
				TDAUX.CEPE_EMP AS CEPE_EMP,
				EMPRESA.RLEG_EMP AS RLEG_EMP,
				EMPRESA.CARGO_LEG_EMP AS CARGO_LEG_EMP,
				EMPRESA.CPF_LEG_EMP AS CPF_LEG_EMP,
				TD_CONTADOR.NOME_CON AS NOME_CON,
				TD_CONTADOR.RCRC_CON AS CRC_CON,
				TD_CONTADOR.CPF_CON AS CPF_CON
		 FROM BETHADBA.EFENTRADAS_EXTRA_PRODUTO AS EFENTRADAS_EXTRA_PRODUTO INNER JOIN
				BETHADBA.EFPRODUTOS AS EFPRODUTOS
			ON EFPRODUTOS.CODI_EMP = EFENTRADAS_EXTRA_PRODUTO.CODI_EMP AND
				EFPRODUTOS.CODI_PDI = EFENTRADAS_EXTRA_PRODUTO.CODIGO_PRODUTO INNER JOIN
				BETHADBA.GEEMPRE AS EMPRESA
			ON EMPRESA.CODI_EMP = EFENTRADAS_EXTRA_PRODUTO.CODI_EMP,
				LATERAL(SELECT MONTH(EFENTRADAS_EXTRA_PRODUTO.DATA_MOVIMENTACAO) AS MES,
									YEAR(EFENTRADAS_EXTRA_PRODUTO.DATA_MOVIMENTACAO) AS ANO,
									CAST(:CIDAEMP AS VARCHAR(255)) AS CIDAEMP,
									CAST(:CEPEEMP AS VARCHAR(8)) AS CEPE_EMP,
									CAST(:ENDEEMP AS VARCHAR(40)) AS ENDE_EMP
							 FROM DSDBA.DUMMY) AS TDAUX,
				LATERAL(SELECT MAX(CONTADOR.NOME_CON) AS NOME_CON,
									MAX(CONTADOR.RCRC_CON) AS RCRC_CON,
									MAX(CONTADOR.CPFC_CON) AS CPF_CON
							 FROM BETHADBA.GECONTADOR AS CONTADOR
							WHERE CONTADOR.CODI_CON = EMPRESA.CODI_CON) AS TD_CONTADOR
		WHERE EFENTRADAS_EXTRA_PRODUTO.CODI_EMP IN (:ALLISTAEMPRESAS) AND
				EFENTRADAS_EXTRA_PRODUTO.DATA_MOVIMENTACAO >= :DATINI AND
				EFENTRADAS_EXTRA_PRODUTO.DATA_MOVIMENTACAO <= :DATFIN AND
				EFPRODUTOS.TIPO_PDI = 'S' AND
				:EXLUIR_CUSTO_AQUISICAO_VEICULO = 'S'
	GROUP BY TDAUX.MES, TDAUX.ANO, TDAUX.ENDE_EMP, EMPRESA.IEST_EMP, TDAUX.CIDAEMP, EMPRESA.CGCE_EMP, TDAUX.CEPE_EMP,
				EMPRESA.RLEG_EMP, EMPRESA.CPF_LEG_EMP, EMPRESA.CARGO_LEG_EMP, TD_CONTADOR.NOME_CON, TD_CONTADOR.RCRC_CON, TD_CONTADOR.CPF_CON
ORDER BY 7, 6